### ISSUE TITLE
NPE in ProfileSubsystem.shutdown()

### ISSUE THREAD

**Issue by SilleBille** [SilleBille/pki#309]
This issue was migrated from [Pagure Issue #2550](https://pagure.io/dogtagpki/issue/2550).Originally filed by gkapoor on 2016-11-16

 SubCA installation fails due to NPE. I have attached logs and other details.

This is seen with a LunaSA machine.

Here we are trying to create a subCA which is signed by existing externalCA

Steps to Reproduce:
```
1.Create a externalCA
2.Now use the attached config files and try to create create a subCA and get it
signed by externalCA
```

Actual results:
```
Nov 07, 2016 6:20:49 AM org.apache.catalina.core.ApplicationContext log
SEVERE: Servlet castart threw unload() exception
javax.servlet.ServletException: Servlet.destroy() for servlet castart threw
exception
    at
org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1505)
    at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.ja
va:1846)
    at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
    at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.ja
va:5767)
    at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
    at
org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1588)
    at
org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1577)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.netscape.cmscore.profile.ProfileSubsystem.shutdown(ProfileSubsystem.
java:225)
    at
com.netscape.cmscore.apps.CMSEngine.shutdownSubsystems(CMSEngine.java:2115)
    at com.netscape.cmscore.apps.CMSEngine.shutdown(CMSEngine.java:2010)
    at com.netscape.certsrv.apps.CMS.shutdown(CMS.java:233)
    at
com.netscape.cms.servlet.base.CMSStartServlet.destroy(CMSStartServlet.java:144)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessor
Impl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:288)
    at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:285)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
    at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:320)
    at
org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:175)
    at
org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:102)
    at
org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1478)
    ... 10 more
```

Expected results:
```
subca should start.Even if there are issues it should give correct log message
rather than NPE.
```

Additional info:
```
logs attached to associated Bugzilla Bug
```

**Comment by SilleBille** [comment]
Posted by vakwetu on 2016-11-29: 

+1 for priority and milestone.

**Comment by SilleBille** [comment]
Posted by mharmsen on 2016-11-30: 

Replying to [comment:3 vakwetu]:
> +1 for priority and milestone.

per offline triage: 10.3 - critical; clearing proposed priority/milestone

**Comment by SilleBille** [comment]
Posted by edewata on 2016-12-08: 

As mentioned in the associated bug, the problem only happens with environment error (e.g. conflicting ports). The shutdown itself is a normal response of that error, but it looks like there's a bug in ProfileSubsystem.shutdown() that prevents a graceful shutdown.

**Comment by SilleBille** [comment]
Posted by mharmsen on 2016-12-14: 

Per comment #4: had been previously marked as 10.3 - critical

**Comment by SilleBille** [comment]
Posted by mharmsen on 2016-12-14: 

Per comment #4: had been previously marked as 10.3 - critical

**Comment by SilleBille** [comment]
Posted by mharmsen on 2016-12-15: 

+1 on revised Milestone and Priority from alee on IRC

**Comment by SilleBille** [comment]
Posted by mharmsen on 2017-10-25: 

[20171025] - Offline Triage ==> 10.6

**Comment by SilleBille** [comment]
Posted by mharmsen on 2018-04-26: 

Per 10.5.x/10.6 Triage:   10.6

alee: error handling cleanup.  QE would like to see a nice error message as opposed to NPE.  Better yet, a test in python installer code for bad ports before it gets to this point.  The python code test is what I would target for 10.6 as a usability improvement.
