### ISSUE TITLE
[MAN] PKI : Pki cli behavior when --ignore-cert-status is added

### ISSUE THREAD

**Issue by SilleBille** [SilleBille/pki#310]
This issue was migrated from [Pagure Issue #2553](https://pagure.io/dogtagpki/issue/2553).Originally filed by gkapoor on 2016-11-22

 man pki says about "--ignore-cert-status" but i tried using it I always get
"Caused by: java.lang.NoSuchFieldException: "

Steps to Reproduce:
```
pki -v -d /opt/rhqa_pki/certdb/ -h pki1.example.com -c Secret123 -p 25080
--ignore-cert-status "TPS_AgentV" -n "TPS_AgentV"  tps-token-find
PKI options: -v -d /opt/rhqa_pki/certdb/
PKI command: pki1.example.com -h pki1.example.com -c Secret123 -p 25080
--ignore-cert-status TPS_AgentV -n TPS_AgentV tps-token-find
Java command: /usr/lib/jvm/jre-1.8.0-openjdk/bin/java
-Djava.ext.dirs=/usr/share/pki/lib
-Djava.util.logging.config.file=/usr/share/pki/etc/logging.properties
com.netscape.cmstools.cli.MainCLI -d /opt/rhqa_pki/certdb/ --verbose -h
pki1.example.com -c Secret123 -p 25080 --ignore-cert-status TPS_AgentV -n
TPS_AgentV tps-token-find
Server URI: http://pki1.example.com:25080
java.lang.Error: Invalid cert status "TPS_AgentV".
        at
com.netscape.cmstools.cli.MainCLI.convertCertStatusList(MainCLI.java:461)
        at com.netscape.cmstools.cli.MainCLI.parseOptions(MainCLI.java:439)
        at com.netscape.cmstools.cli.MainCLI.execute(MainCLI.java:540)
        at com.netscape.cmstools.cli.MainCLI.main(MainCLI.java:574)
Caused by: java.lang.NoSuchFieldException: TPS_AgentV
        at java.lang.Class.getField(Class.java:1703)
        at
com.netscape.cmstools.cli.MainCLI.convertCertStatusList(MainCLI.java:457)
        ... 3 more
ERROR: Command '[u'/usr/lib/jvm/jre-1.8.0-openjdk/bin/java',
u'-Djava.ext.dirs=/usr/share/pki/lib',
u'-Djava.util.logging.config.file=/usr/share/pki/etc/logging.properties',
'com.netscape.cmstools.cli.MainCLI', '-d', '/opt/rhqa_pki/certdb/',
'--verbose', '-h', 'pki1.example.com', '-c', 'Secret123', '-p', '25080',
'--ignore-cert-status', 'TPS_AgentV', '-n', 'TPS_AgentV', 'tps-token-find']'
returned non-zero exit status 25
```

**Comment by SilleBille** [comment]
Posted by edewata on 2016-11-29: 

The --reject-cert-status and --ignore-cert-status parameters should actually be followed by a list of statuses to reject/ignore. The possible values are defined in ValidityStatus class in JSS:


- EXPIRED_CERTIFICATE
- REVOKED_CERTIFICATE
- INADEQUATE_KEY_USAGE
- INADEQUATE_CERT_TYPE
- UNTRUSTED_CERT
- CERT_STATUS_SERVER_ERROR
- UNKNOWN_ISSUER
- UNTRUSTED_ISSUER
- CERT_NOT_IN_NAME_SPACE
- CA_CERT_INVALID
- PATH_LEN_CONSTRAINT_INVALID
- BAD_KEY
- BAD_SIGNATURE
- EXPIRED_ISSUER_CERTIFICATE
- INVALID_TIME
- UNKNOWN_SIGNER
- SEC_ERROR_CRL_EXPIRED
- SEC_ERROR_CRL_BAD_SIGNATURE
- SEC_ERROR_CRL_INVALID
- CERT_BAD_ACCESS_LOCATION
- OCSP_UNKNOWN_RESPONSE_TYPE
- OCSP_BAD_HTTP_RESPONSE
- OCSP_MALFORMED_REQUEST
- OCSP_SERVER_ERROR
- OCSP_TRY_SERVER_LATER
- OCSP_REQUEST_NEEDS_SIG
- OCSP_UNAUTHORIZED_REQUEST
- OCSP_UNKNOWN_RESPONSE_STATUS
- OCSP_UNKNOWN_CERT
- OCSP_NOT_ENABLED
- OCSP_NO_DEFAULT_RESPONDER
- OCSP_MALFORMED_RESPONSE
- OCSP_UNAUTHORIZED_RESPONSE
- OCSP_FUTURE_RESPONSE
- OCSP_OLD_RESPONSE
- BAD_CERT_DOMAIN


Since there are quite a few possible values, it should be documented in the pki man page (instead of CLI help message). The CLI itself is already generating the proper error message:

 Error: Invalid cert status "TPS_AgentV"

**Comment by SilleBille** [comment]
Posted by vakwetu on 2016-11-29: 

Seems like a quick fix.

+1 for priority and milestone

**Comment by SilleBille** [comment]
Posted by mharmsen on 2016-11-30: 

Replying to [comment:4 vakwetu]:
> Seems like a quick fix.
> 
> +1 for priority and milestone

per offline triage: 10.3 - major; clearing proposed priority/milestone

**Comment by SilleBille** [comment]
Posted by mharmsen on 2017-02-09: 

Per PKI Bug Council of 02/09/2017: 10.3 => 10.4

**Comment by SilleBille** [comment]
Posted by mharmsen on 2017-10-25: 

[20171025] - Offline Triage ==> 10.6
