### ISSUE TITLE
Port to resteasy 3.1.0

### ISSUE THREAD

**Issue by SilleBille** [SilleBille/pki#319]
This issue was migrated from [Pagure Issue #2596](https://pagure.io/dogtagpki/issue/2596).Originally filed by tjaalton on 2017-02-15

 Resteasy 3.1.0 moved ClientResponseType to resteasy-legacy.jar, so dogtag needs to either use something else or use the legacy jar.

**Comment by SilleBille** [comment]
Posted by tjaalton on 2017-02-15: 

I don't know if that patch is enough, but at least it builds now.

**Comment by SilleBille** [comment]
Posted by tjaalton on 2017-02-15: 

fix javadoc build
[use-resteasy-legacy.diff](/dogtagpki/issue/raw/files/94cd9d22b23e5712a61577c4d4cda174459c52bda4c21af6a23fda595ec627c3-use-resteasy-legacy.diff)

**Comment by SilleBille** [comment]
Posted by tjaalton on 2017-02-18: 

this patch is not enough, pkispawn still fails with just

Log file: /var/log/pki/pki-ca-spawn.20170217194720.log
Loading deployment configuration from /tmp/pkispawn.config.
Installing CA into /var/lib/pki/pki-tomcat.
Storing deployment configuration into /etc/dogtag/tomcat/pki-tomcat/ca/deployment.cfg.
[ ok ] Starting pki-tomcatd (via systemctl): pki-tomcatd.service.

Installation failed:
Traceback (most recent call last):
  File "/usr/sbin/pkispawn", line 817, in <module>
    main(sys.argv)
  File "/usr/sbin/pkispawn", line 535, in main
    if r.headers['content-type'] == 'application/json':
  File "/usr/lib/python2.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'

and nothing in the logs that I could find relevant

**Comment by SilleBille** [comment]
Posted by edewata on 2017-02-24: 

According to tjaalton this problem affects Debian testing (9.0 to be) and unstable, and Ubuntu 17.04.

Fedora/RHEL is still using Resteasy 3.0.x.

**Comment by SilleBille** [comment]
Posted by mharmsen on 2017-04-04: 

Moving to 10.4 critical for now although this will probably not be addressed immediately.

**Comment by SilleBille** [comment]
Posted by mharmsen on 2017-04-24: 

Per CS/DS meeting of 04/24/2017:  10.5 critical

**Comment by SilleBille** [comment]
Posted by mharmsen on 2017-10-25: 

[20171025] - Offline Triage ==> 10.6

**Comment by SilleBille** [comment]
Posted by tjaalton on 2017-11-10: 

I see 10.5 was recently released. When is 10.6 expected to come out? Feature freeze of Ubuntu 18.04 is in 2018-03-01: https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule

So having this and https://pagure.io/dogtagpki/issue/2560 fixed by that date would help to ensure 18.04 LTS would still ship freeipa server.

**Comment by SilleBille** [comment]
Posted by tjaalton on 2018-02-28: 

[![use-resteasy-legacy.diff](/dogtagpki/issue/raw/files/4110541be252f207cbf600fbb614dd78f6af1e273bb61591803975db5e83fe13-use-resteasy-legacy.diff)](/dogtagpki/issue/raw/files/4110541be252f207cbf600fbb614dd78f6af1e273bb61591803975db5e83fe13-use-resteasy-legacy.diff)

Here's a slightly updated version of the patch. Pkispawn now fails with this:

Installation failed:
<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.46 (Debian) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 500 - Servlet execution threw an exception</h1><div class="line"></div><p><b>type</b> Exception report</p><p><b>message</b> <u>Servlet execution threw an exception</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b></p><pre>javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
</pre><p><b>root cause</b></p><pre>java.lang.AbstractMethodError: javax.ws.rs.core.Response$ResponseBuilder.status(ILjava/lang/String;)Ljavax/ws/rs/core/Response$ResponseBuilder;
	javax.ws.rs.core.Response$ResponseBuilder.status(Response.java:921)
	javax.ws.rs.core.Response.status(Response.java:592)
	javax.ws.rs.core.Response.status(Response.java:603)
	javax.ws.rs.core.Response.ok(Response.java:638)
	javax.ws.rs.core.Response.ok(Response.java:650)
	org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:353)
	org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
</pre><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/8.0.46 (Debian) logs.</u></p><hr class="line"><h3>Apache Tomcat/8.0.46 (Debian)</h3></body></html>

Please check the CA logs in /var/log/pki/pki-tomcat/ca.
