### ISSUE TITLE
Removing the --renewal option while placing Cert renewal request from CLI

### ISSUE THREAD

**Issue by SilleBille** [SilleBille/pki#353]
This issue was migrated from [Pagure Issue #2752](https://pagure.io/dogtagpki/issue/2752).Originally filed by dmoluguw on 2017-06-22

 When submitting a renewal request from CLI using the following command,  `PKIException: Policy Set Not Found` is produced.

       pki ca-cert-request-submit --profile caManualRenewal --serial 0x2  # OCSP signing
The log in /var/log/pki/pki-tomcat/ca/debug: 

    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: EnrollmentProcessor: set Inputs into profile Context
    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: EnrollmentProcessor: set sslClientCertProvider
    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: EnrollProfile: createRequests: begins
    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: EnrollProfile: createRequests:  request type is null
    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: Repository: in getNextSerialNumber. 
    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: Repository: checkRange  mLastSerialNo=12
    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: Repository: getNextSerialNumber: returning retSerial 12
    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: EnrollProfile: setDefaultCertInfo: setting issuerDN using exact CA signing cert subjectDN encoding
    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: EnrollProfile: createEnrollmentRequest 12
    [22/Jun/2017:14:42:23][http-nio-8080-exec-6]: CertProcessor: no profile policy set found
    Policy Set Not Found
	at com.netscape.cms.servlet.cert.CertProcessor.populateRequests(CertProcessor.java:362)
	at com.netscape.cms.servlet.cert.EnrollmentProcessor.processEnrollment(EnrollmentProcessor.java:188)
	at com.netscape.cms.servlet.cert.EnrollmentProcessor.processEnrollment(EnrollmentProcessor.java:96)
	at com.netscape.cms.servlet.cert.CertRequestDAO.submitRequest(CertRequestDAO.java:195)
	at org.dogtagpki.server.ca.rest.CertRequestService.enrollCert(CertRequestService.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:293)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:290)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:325)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:176)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:286)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:56)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:185)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:293)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:290)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:549)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:325)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:264)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
	at org.apache.catalina.core.ApplicationFilterChain.access$000(ApplicationFilterChain.java:56)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain$1.run(ApplicationFilterChain.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:185)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at com.netscape.cms.tomcat.ExternalAuthenticationValve.invoke(ExternalAuthenticationValve.java:78)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at     org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

But, when the above command is executed with `--renewal` option, it works as expected:

    pki ca-cert-request-submit --profile caManualRenewal --serial 0x2  --renewal
    -----------------------------
    Submitted certificate request
    -----------------------------
    Request ID: 17
    Type: renewal
    Request Status: pending
    Operation Result: success

Expected: `--renewal` shouldn't be included as part of the CLI command as the profile being used is for renewal

Reference: http://pki.fedoraproject.org/wiki/System_Certificate_Renewal#Submitting_Renewal_Requests

**Comment by SilleBille** [comment]
Posted by mharmsen on 2017-10-25: 

[20171025] - Offline Triage ==> 10.6

**Comment by SilleBille** [comment]
Posted by amolkahat on 2018-04-05: 

Updated the Wiki: http://www.dogtagpki.org/wiki/System_Certificate_Renewal#PKI_10.4_or_later

**Comment by SilleBille** [comment]
Posted by mharmsen on 2018-05-02: 

 Per 10.5.x/10.6 Triage:   10.6

edewata: usability issue. there's a workaround.
